FROM nginx:latest
WORKDIR /usr/app 

COPY build /usr/app/html
COPY nginx.conf.dev /etc/nginx/sites-available/nginx.conf

RUN rm -f /etc/nginx/sites-available/default
RUN rm -f /etc/nginx/conf.d/default
RUN mkdir -p /etc/nginx/sites-enabled
RUN ln -s -f /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled/nginx.conf

RUN mkdir -p /usr/share/nginx/html
RUN cp -r /usr/app/html/* /usr/share/nginx/html
RUN ln -s -f /etc/nginx/sites-available/nginx.conf /etc/nginx/conf.d/nginx.conf

RUN mkdir -p ssl
