FROM python:3.9
WORKDIR /backend
COPY requirements.txt /backend/requirements.txt
RUN pip install -r requirements.txt
COPY config /backend/config
COPY api /backend/api
COPY beafamily /backend/beafamily
COPY manage.py /backend/manage.py
COPY create_dummy.py /backend/create_dummy.py
COPY dummy /backend/dummy

ENV DJANGO_SETTINGS_MODULE="config.dev_settings"

RUN mkdir -p logs
RUN mkdir -p data
RUN mv dummy data
RUN python manage.py makemigrations 
RUN python manage.py migrate
RUN python create_dummy.py
