on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    dev_deploy:
        runs-on: ubuntu-latest
        name: Deploy to Development Server

        permissions:
            contents: "read"
            id-token: "write"

        steps:
            # actions/checkout MUST come before auth
            - uses: "actions/checkout@v3"

            - id: "auth"
              uses: "google-github-actions/auth@v1"
              with:
                  workload_identity_provider: ${{ secrets.DEV_DEPLOY_PROVIDER }}
                  service_account: ${{ secrets.DEV_DEPLOY_ACCOUNT }}

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v1"

            - name: "Deploy"
              uses: "google-github-actions/ssh-compute@v0"
              with:
                  instance_name: "dev-deploy@dev-deploy"
                  zone: "asia-northeast3-a"
                  ssh_private_key: "${{ secrets.DEV_DEPLOY_KEY }}"
                  command: "$HOME/deploy.sh"
